create table game (
    id int8 generated by default as identity,
    platform varchar(255) not null,
    title varchar(255) not null,
    genre_id int8,
    primary key (id)
);

create table genre (
    id int8 generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table record (
    id int8 generated by default as identity,
    age int4,
    email varchar(255) not null,
    moment timestamp not null,
    name varchar(255) not null,
    game_id int8,
    primary key (id)
);

alter table if exists record add constraint uk_record_email unique (email);

alter table if exists game add constraint fk_game_genre foreign key (genre_id) references genre;

alter table if exists record add constraint fk_record_game foreign key (game_id) references game;